image: registry.gitlab.com/aboutbits/docker-inside-docker:19

services:
  - docker:19-dind

stages:
  - setup
  - test

cache:
  paths:
    - node_modules

before_script:
  - docker network create proxy

setup:
  stage: setup
  script:
    - docker-compose run --rm -T node npm ci

lint:
  stage: test
  script:
    - docker-compose run --rm -T node npm run lint

test:
  stage: test
  script:
    - docker-compose run --rm -T node npm run test
